version: "3"

services:
  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
    container_name: redis-infomansion
    volumes:
      - redis-volumes:/data
      - ./redis/conf/redis.conf:/etc/redis/redis.conf
    restart: always
    ports:
      - "6379:6379"

volumes:
  redis-volumes:
