version: "3"

services:
  redis:
    image: redis
    container_name: redis-infomansion
    volumes:
      - redis-volumes:/data
    restart: always
    ports:
      - "6379:6379"

volumes:
  redis-volumes:
