version: "3"

networks:
  blue-front-networks:
    driver: bridge
  blue-back-networks:
    driver: bridge

services:
  spring-blue-1:
    container_name: spring-infomansion-blue-1
    image: chiyongs/infomansion:spring
    restart: always
    ports:
      - "8081:8080"
    networks:
      - blue-back-networks
      - blue-front-networks

  spring-blue-2:
    container_name: spring-infomansion-blue-2
    image: chiyongs/infomansion:spring
    restart: always
    ports:
      - "8082:8080"
    networks:
      - blue-back-networks
      - blue-front-networks

  react-blue-1:
    container_name: react-infomansion-blue-1
    image: chiyongs/infomansion:react
    restart: always
    ports:
      - "3001:3000"
    networks:
      - blue-front-networks
      - blue-back-networks

  react-blue-2:
    container_name: react-infomansion-blue-2
    image: chiyongs/infomansion:react
    restart: always
    ports:
      - "3002:3000"
    networks:
      - blue-front-networks
      - blue-back-networks
