version: "3"

networks:
  green-front-networks:
    driver: bridge
  green-back-networks:
    driver: bridge

services:
  spring-green-1:
    container_name: spring-infomansion-green-1
    image: chiyongs/infomansion:spring
    restart: always
    ports:
      - "8001:8080"
    networks:
      - green-back-networks
      - green-front-networks

  spring-green-2:
    container_name: spring-infomansion-green-2
    image: chiyongs/infomansion:spring
    restart: always
    ports:
      - "8002:8080"
    networks:
      - green-back-networks
      - green-front-networks

  react-green-1:
    container_name: react-infomansion-green-1
    image: chiyongs/infomansion:react
    restart: always
    ports:
      - "3031:3000"
    networks:
      - green-front-networks
      - green-back-networks

  react-green-2:
    container_name: react-infomansion-green-2
    image: chiyongs/infomansion:react
    restart: always
    ports:
      - "3032:3000"
    networks:
      - green-front-networks
      - green-back-networks
