version: "3"

# networks:
#   front-networks:
#     driver: bridge
#   back-networks:
#     driver: bridge

services:
  jenkins:
    container_name: jenkins-compose
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    user: root
    ports:
      - "32773:8080"
      - "50000:50000"
    volumes:
      - /home/ubuntu/compose/jenkins:/var/jenkins_home
      - /home/ubuntu/compose/.ssh:/root/.ssh
#   spring-1:
#     container_name: spring-infomansion-1
#     build:
#       context: ./backend
#       dockerfile: Dockerfile.prod
#     restart: always
#     ports:
#       - "8081:8080"
#     networks:
#       - back-networks
#       - front-networks
#     depends_on:
#       - redis

#   spring-2:
#     container_name: spring-infomansion-2
#     build:
#       context: ./backend
#       dockerfile: Dockerfile.prod
#     restart: always
#     ports:
#       - "8082:8080"
#     networks:
#       - back-networks
#       - front-networks
#     depends_on:
#       - redis

#   redis:
#     image: redis
#     container_name: redis-infomansion
#     volumes:
#       - redis-volumes:/data
#     restart: always
#     expose:
#       - "6379"
#     networks:
#       - back-networks

#   react-1:
#     container_name: react-infomansion-1
#     build:
#       context: ./frontend
#       dockerfile: Dockerfile.prod
#     restart: always
#     ports:
#       - "3001:3000"
#     networks:
#       - front-networks
#       - back-networks

#   react-2:
#     container_name: react-infomansion-2
#     build:
#       context: ./frontend
#       dockerfile: Dockerfile.prod
#     restart: always
#     ports:
#       - "3002:3000"
#     networks:
#       - front-networks
#       - back-networks

# volumes:
#   redis-volumes:
