FROM openjdk:11-jre-slim

WORKDIR /app

ARG JAR_FILE=./build/libs/server-0.0.1-SNAPSHOT.jar

COPY ${JAR_FILE} /app/app.jar

EXPOSE 8080

ENTRYPOINT ["java","-jar","-Dspring.profiles.active=prod","app.jar"]