spring:
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

  output:
    ansi:
      enabled: always

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 465
    username: contactinfomansion@gmail.com
    password: szdwttmotcygfloo
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          debug: true
          ssl:
            enable: true
    redirectURI: http://localhost:8080/test/success

logging:
  level:
    com:
      infomansion:
        server: debug

jwt:
  secret: dGhpcy1pcy1hLXRlbXAtc2VjcmV0LWtleS1mb3ItaW5mby1tYW5zaW9uLWluLXNzYWZ5LTd0aC1ieS1jaGl5b25ncy1sZXRzZ29pbmZvbWFuc2lvbgo=

---
spring:
  profiles:
    active: dev
---
spring:
  profiles:
    active: local
    default: local
