spring:
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

  output:
    ansi:
      enabled: always

  config:
    import:
      - optional:classpath:/jwt.yml
      - optional:classpath:/mail.yml

logging:
  level:
    com:
      infomansion:
        server: debug

---
spring:
  profiles:
    active: dev

---
spring:
  profiles:
    active: prod

---
spring:
  profiles:
    active: local
    default: local
