spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://host.docker.internal:3309/infomansion?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: infomansion
    password: infomansion

  redis:
    host: host.docker.internal
    port: 6380
