cloud:
  aws:
    stack:
      auto: false
    region:
      static: ap-northeast-2
    credentials:
      access-key: AKIASJRN5KGTJSDN3WXL
      secret-key: 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
    s3:
      bucket: infomansion-webservice-s3
      bucketUrl: https://infomansion-webservice-s3.s3.ap-northeast-2.amazonaws.com