spring:
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

  output:
    ansi:
      enabled: always

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/infomansion?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: infomansion
    password: infomansion

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  redis:
    host: localhost
    port: 6379

logging:
  level:
    com:
      infomansion:
        server: debug

jwt:
  secret: dGhpcy1pcy10ZW1wLXNlY3JldC1rZXktZm9yLWluZm8tbWFuc2lvbgo=

---
#################
# test 환경      #
#################
