spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url:
    username:
    password:

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MariaDB106Dialect

  redis:
    host: i7a607.p.ssafy.io
    port: 6379

  mail:
    redirectURI: https://i7a607.p.ssafy.io/
    verificationLink:

infomansion:
  cookie:
    domain: i7a607.p.ssafy.io
