spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/infomansion?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: infomansion
    password: infomansion

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  redis:
    host: localhost
    port: 6379

  mail:
    redirectURI: http://localhost:8080
    verificationLink: http://localhost:8080/api/v1/auth/verification?key=

infomansion:
  cookie:
    domain: localhost
