spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url:
    username:
    password:

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MariaDB106Dialect

  redis:
    host: host.docker.internal
    port: 6380

  mail:
    redirectURI: http://localhost:3000
    verificationLink:

infomansion:
  cookie:
    domain: localhost