/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/stand_small.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.low_poly_interior283.geometry} material={materials.low_poly_interior} position={[9.34, 0.72, -22.39]} rotation={[-Math.PI, -0.79, -0.3]} scale={100} />
    </group>
  )
}

useGLTF.preload('/stand_small.gltf')
