/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/table_side_black_1.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.low_poly_interior1889.geometry} material={materials.low_poly_interior} position={[-11.5, 42.99, -14.42]} rotation={[Math.PI, 0, -Math.PI]} scale={100} />
      <mesh geometry={nodes.low_poly_interior1890.geometry} material={materials.low_poly_interior} position={[-11.46, 43.66, -14.47]} rotation={[0, 0, -Math.PI / 2]} scale={100} />
      <mesh geometry={nodes.low_poly_interior1891.geometry} material={materials.low_poly_interior} position={[-11.73, 43.65, -14.34]} rotation={[-Math.PI, -0.35, -0.3]} scale={100} />
    </group>
  )
}

useGLTF.preload('/table_side_black_1.glb')
