/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/table_brown_small_1.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.low_poly_interior1896.geometry} material={materials.low_poly_interior} position={[-11.42, 43, -12.64]} rotation={[0, 1.57, 0]} scale={100} />
      <mesh geometry={nodes.low_poly_interior1897.geometry} material={materials.low_poly_interior} position={[-11.62, 43.61, -12.31]} rotation={[0, -0.29, -Math.PI / 2]} scale={100} />
      <mesh geometry={nodes.low_poly_interior1898.geometry} material={materials.low_poly_interior} position={[-11.68, 43.57, -12.89]} rotation={[0, 0, -Math.PI / 2]} scale={100} />
    </group>
  )
}

useGLTF.preload('/table_brown_small_1.glb')
