/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/stuffAssets/shelf_white_medium_1.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.low_poly_interior1899.geometry} material={materials.low_poly_interior} position={[-8.71, 43, -15.95]} scale={100} />
      <mesh geometry={nodes.low_poly_interior1910.geometry} material={materials.low_poly_interior} position={[-8.56, 43.1, -15.74]} rotation={[0, -0.54, -Math.PI / 2]} scale={100} />
      <mesh geometry={nodes.low_poly_interior1911.geometry} material={materials.low_poly_interior} position={[-8.5, 43.31, -15.7]} rotation={[0, -0.68, -Math.PI / 2]} scale={100} />
      <mesh geometry={nodes.low_poly_interior1912.geometry} material={materials.low_poly_interior} position={[-8.37, 43.61, -15.7]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={100} />
      <mesh geometry={nodes.low_poly_interior1913.geometry} material={materials.low_poly_interior} position={[-8.59, 45.31, -15.72]} rotation={[0, -1.24, -Math.PI / 2]} scale={100} />
      <mesh geometry={nodes.low_poly_interior1914.geometry} material={materials.low_poly_interior} position={[-8.6, 44.51, -15.7]} rotation={[0, -1.32, -Math.PI / 2]} scale={100} />
      <mesh geometry={nodes.low_poly_interior1915.geometry} material={materials.low_poly_interior} position={[-8.54, 43.99, -15.74]} rotation={[Math.PI, -1.4, Math.PI / 2]} scale={100} />
      <mesh geometry={nodes.low_poly_interior1916.geometry} material={materials.low_poly_interior} position={[-8.34, 44.77, -15.75]} rotation={[Math.PI, -1.53, 1.57]} scale={100} />
    </group>
  )
}

useGLTF.preload('/stuffAssets/shelf_white_medium_1.glb')
