/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/stuffAssets/wall_1.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.low_poly_interior1892.geometry} material={materials.low_poly_interior} position={[-12.08, 44.29, -14.67]} scale={100} />
      <mesh geometry={nodes.low_poly_interior1893.geometry} material={materials.low_poly_interior} position={[-12.08, 44.29, -13.85]} scale={100} />
      <mesh geometry={nodes.low_poly_interior1894.geometry} material={materials.low_poly_interior} position={[-12.08, 44.26, -14.34]} scale={100} />
      <mesh geometry={nodes.low_poly_interior1906.geometry} material={materials.low_poly_interior} position={[-10.72, 44.89, -16]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={100} />
      <mesh geometry={nodes.low_poly_interior1907.geometry} material={materials.low_poly_interior} position={[-10.51, 45.5, -15.83]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={100} />
      <mesh geometry={nodes.low_poly_interior1908.geometry} material={materials.low_poly_interior} position={[-10.14, 45.4, -15.87]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={100} />
      <mesh geometry={nodes.low_poly_interior1917.geometry} material={materials.low_poly_interior} position={[-10, 45, -14]} scale={100} />
      <mesh geometry={nodes.low_poly_interior1919.geometry} material={materials.low_poly_interior} position={[-12.07, 44.15, -14]} scale={100} />
      <mesh geometry={nodes.low_poly_interior1921.geometry} material={materials.low_poly_interior} position={[-10, 45, -14]} scale={100} />
      <mesh geometry={nodes.low_poly_interior1924.geometry} material={materials.low_poly_interior} position={[-11.96, 43.9, -15.96]} scale={100} />
      <mesh geometry={nodes.low_poly_interior1930.geometry} material={materials.low_poly_interior} position={[-9.39, 45.12, -15.98]} rotation={[Math.PI / 2, 0, 0]} scale={100} />
    </group>
  )
}

useGLTF.preload('/stuffAssets/wall_1.glb')
