/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/stuffAssets/map_ini.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.room_ini.geometry} material={nodes.room_ini.material} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/stuffAssets/map_ini.gltf')
