/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ Hover, Click, ...props }) {
  const [name, setName] = useState("Table_wood_1");
  
  // 부모객체의 호버, 클릭 함수 호출
  function onHover() { Hover(name); }
  function onClick() { Click(name); }

  const group = useRef()
  const { nodes, materials } = useGLTF('/stuffAssets/table_wood_1.glb')
  return (
    <group 
      onPointerOver={() => onHover()} 
      onPointerDown={() => onClick()}
      
      ref={group} dispose={null}
      castShadow
      {...props}
    >
      <mesh geometry={nodes.low_poly_interior1901.geometry} material={materials.low_poly_interior} position={[-9.06, 43, -13.13]} rotation={[0, 0.95, 0]} scale={100} />
      <mesh geometry={nodes.low_poly_interior1903.geometry} material={materials.low_poly_interior} position={[-8.72, 43.83, -13.73]} rotation={[0, -1.27, 0]} scale={100} />
      <mesh geometry={nodes.low_poly_interior1904.geometry} material={materials.low_poly_interior} position={[-9.12, 43.78, -13.08]} rotation={[0, -0.73, 0]} scale={100} />
      <mesh geometry={nodes.low_poly_interior1931.geometry} material={materials.low_poly_interior} position={[-8.91, 43.77, -13.56]} rotation={[0, -0.55, -Math.PI / 2]} scale={100} />
    </group>
  )
}

useGLTF.preload('/stuffAssets/table_wood_1.glb')
